In [1]:
import tensorflow as tf

In [13]:
tensor_index = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(tensor_index)
print(tensor_index[0:3:2])

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)
tf.Tensor([1 3], shape=(2,), dtype=int32)


In [17]:
tensor_index = tf.constant([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9], 
    [10, 11, 12]
        
    ])
print(tensor_index)

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)


In [19]:
# INDEXING MULTIPLE DIMENSIONS (2D)
# PRINT(tensor_index[rows , columns])
print(tensor_index[0:3, 0:2])

tf.Tensor(
[[1 2]
 [4 5]
 [7 8]], shape=(3, 2), dtype=int32)


In [20]:
print(tensor_index[0:3, :])

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [24]:
print(tensor_index[1,0])

tf.Tensor(4, shape=(), dtype=int32)


In [25]:
print(tensor_index[2, :])

tf.Tensor([7 8 9], shape=(3,), dtype=int32)


In [34]:
print(tensor_index[2, :2])

tf.Tensor([7 8], shape=(2,), dtype=int32)


In [40]:
print(tensor_index)

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)


In [43]:
print(tensor_index[:4, 1])

tf.Tensor([ 2  5  8 11], shape=(4,), dtype=int32)


In [37]:
print(tensor_index[..., 1])

tf.Tensor([ 2  5  8 11], shape=(4,), dtype=int32)


### INDEXING MULTIPLE DIMENSIONS (3D)
### PRINT(tensor_index[first d , second d, third d])

### OR 

### PRINT(tensor_index[SPECIFIC TENSOR , SPECIFIC ROW, SPECIFIC COLUMN ])


In [46]:
tensor_3D = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ], 
    [
        [13, 14, 15],
        [16, 17, 18]
    ], 
    [
        [19, 20, 21],
        [22, 23, 24]
    ]
])
print(tensor_3D)
print(tensor_3D.shape)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]], shape=(4, 2, 3), dtype=int32)
(4, 2, 3)


In [47]:
print(tensor_3D[0, : , : ])

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [52]:
print(tensor_3D[0, 0 , : ])


tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [53]:
print(tensor_3D[0, : , -1 ])
# getting last column in first tensor in 3D tensor

tf.Tensor([3 6], shape=(2,), dtype=int32)


In [54]:
print(tensor_3D[0:2, : , 2 ])


tf.Tensor(
[[ 3  6]
 [ 9 12]], shape=(2, 2), dtype=int32)


In [55]:
print(tensor_3D[ ... , : , 2])

tf.Tensor(
[[ 3  6]
 [ 9 12]
 [15 18]
 [21 24]], shape=(4, 2), dtype=int32)
