In [2]:
import tensorflow as tf

In [3]:
tensor_zeroD = tf.constant(4)
print(tensor_zeroD)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_1D = tf.constant([1, 2, 3, 4, 5])
print(tensor_1D)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [6]:
tensor_2D = tf.constant([
    [1, 2, 3], 
    [4, 5, 6]
    ])
print(tensor_2D)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [7]:
tensor_3D = tf.constant([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
    ])
print(tensor_3D)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [8]:
print(tensor_3D.shape)

(2, 2, 3)


In [9]:
print(tensor_3D.dtype)

<dtype: 'int32'>


In [10]:
print(tensor_3D.ndim)

3


In [11]:
tensor_4D = tf.constant([
    [
        [[1, 2, 3], [4, 5, 6]],
        [[7, 8, 9], [10, 11, 12]]
    ],
    [
        [[13, 14, 15], [16, 17, 18]],
        [[19, 20, 21], [22, 23, 24]]
    ]
    ])
print(tensor_4D)

tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]], shape=(2, 2, 2, 3), dtype=int32)


In [12]:
print(tensor_4D.shape)

(2, 2, 2, 3)


In [13]:
tensor_one_d = tf.constant([2, 0., -3, 8, 90], dtype=tf.float32)

casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.int16)

print(tensor_one_d.dtype)
print(casted_tensor_one_d.dtype)

<dtype: 'float32'>
<dtype: 'int16'>


In [15]:
tensor_one_d = tf.constant([2, 0., -3, 8, 90], dtype=tf.float32)

casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.bool)

print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [19]:
tensor_string = tf.constant(["TensorFlow"])
print(tensor_string)


tf.Tensor([b'TensorFlow'], shape=(1,), dtype=string)


In [18]:
tensor_bool = tf.constant([True, False, False])
print(tensor_bool)

tf.Tensor([ True False False], shape=(3,), dtype=bool)


In [20]:
import numpy as np

In [21]:
np_array = np.array([1, 2, 3, 4, 5])
print(np_array)

[1 2 3 4 5]


In [23]:
converted_tensor = tf.convert_to_tensor(np_array, dtype=tf.float32)
print(converted_tensor)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


In [29]:
eye_tensor = tf.eye(
    num_rows = 5, 
    num_columns=None,
    batch_shape=[3,],
    dtype=tf.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(3, 5, 5), dtype=float32)


In [31]:
fill_tensor = tf.fill([2,3], 8, name=None)
print(fill_tensor)

tf.Tensor(
[[8 8 8]
 [8 8 8]], shape=(2, 3), dtype=int32)


In [33]:
ones_tensor = tf.ones([3,4, 2], 
                      dtype=tf.float32,
                      name=None)
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(3, 4, 2), dtype=float32)


In [35]:
ones_like_tensor = tf.ones_like(fill_tensor, dtype=None, name=None)
print(ones_like_tensor)

tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [36]:
zero_tensors = tf.zeros([3, 4, 2], dtype=tf.float32, name=None)
print(zero_tensors)

tf.Tensor(
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]], shape=(3, 4, 2), dtype=float32)


In [37]:
tf.shape(zero_tensors)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 2], dtype=int32)>

In [39]:
rank_tensor = tf.rank(zero_tensors)
print(rank_tensor)

tf.Tensor(3, shape=(), dtype=int32)


In [40]:
tf.size(zero_tensors)


<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [41]:
random_tensor = tf.random.normal(
    shape=[3, 4, 2],
    mean=0.0,
    stddev=1.0,
    dtype=tf.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[[ 1.725452   -0.24347119]
  [ 0.4175942  -1.0305343 ]
  [-0.4959406   0.20791422]
  [-0.88749814  0.45734534]]

 [[ 0.18651475  0.28548813]
  [ 1.1993537  -0.77439046]
  [ 0.42924285  2.073633  ]
  [ 0.21665277 -1.037458  ]]

 [[ 0.04942915 -0.7807917 ]
  [-0.9760442   0.08648749]
  [ 0.22311872  0.24288867]
  [-0.9414213  -0.34053645]]], shape=(3, 4, 2), dtype=float32)


In [42]:
random_uniform_tensor = tf.random.uniform(
    shape=[3, 4, 2],
    minval=0,
    maxval=None,
    dtype=tf.float32,
    seed=None,
    name=None
)
print(random_uniform_tensor)

tf.Tensor(
[[[0.6457629  0.49272215]
  [0.48299122 0.74737847]
  [0.81314576 0.15257323]
  [0.8532585  0.39784658]]

 [[0.1639787  0.11618865]
  [0.36638832 0.81799746]
  [0.34699488 0.06375766]
  [0.04603088 0.9111712 ]]

 [[0.39854693 0.22016466]
  [0.9583236  0.5150825 ]
  [0.5604608  0.863827  ]
  [0.48744547 0.34443545]]], shape=(3, 4, 2), dtype=float32)
